INSERT INTO CATEGORIES (CATEGORYNAME, CATEGORYDESCRIPTION)
VALUES ('Category one','Description one'),
       ('Category two','Description two'),
       ('Category three','Description three'),
       ('Category four','Description four'),
       ('Category five','Description five');

INSERT INTO PRODUCTS (PRODUCTNAME, PRODUCTDESCRIPTION, PRODUCTPRICE, DISCONTINUED, CATEGORYID)
VALUES
('Chick Peas - Canned', 'luctus nec molestie sed justo', 608.36, false, 5),
('Bay Leaf', 'eros suspendisse accumsan tortor quis turpis sed', 994.09, true, 1),
('Ginger - Ground', 'iaculis congue vivamus metus arcu', 600.23, true, 5),
('Nutmeg - Ground', 'non sodales sed tincidunt eu', 651.06, false, 4),
('Pear - Prickly', 'tortor sollicitudin mi sit amet', 333.16, false, 4),
('Bandage - Flexible Neon', 'ut at dolor quis odio', 517.95, false, 1),
('Cheese - Gouda Smoked', 'felis eu sapien cursus vestibulum proin eu mi', 328.62, false, 2),
('Peas - Pigeon, Dry', 'sit amet justo morbi ut odio cras mi', 794.93, true, 4),
('Tomato Paste', 'a nibh in quis justo', 184.08, false, 2),
('Wine - Chablis 2003 Champs', 'volutpat eleifend donec ut dolor morbi vel lectus', 729.71, false, 3),
('Rabbit - Legs', 'velit nec nisi vulputate nonummy maecenas tincidunt', 652.9, false, 3),
('Onions - Pearl', 'justo eu massa donec dapibus', 834.72, false, 4),
('Extract - Rum', 'mi integer ac neque duis bibendum', 150.43, true, 2),
('Containter - 3oz Microwave Rect.', 'sed nisl nunc rhoncus dui vel sem', 958.55, false, 4),
('Cranberries - Frozen', 'tortor quis turpis sed ante vivamus tortor', 848.8, false, 4),
('Puree - Guava', 'proin eu mi nulla ac enim in tempor', 531.26, true, 4),
('Tart - Butter Plain Squares', 'consequat morbi a ipsum integer', 283.37, true, 2),
('Lettuce - Belgian Endive', 'morbi sem mauris laoreet ut', 707.55, true, 5),
('Wine - Kwv Chenin Blanc South', 'cras non velit nec nisi vulputate', 849.95, false, 5),
('Soup - Campbells Mushroom', 'dolor sit amet consectetuer adipiscing', 582.44, true, 3),
('Tabasco Sauce, 2 Oz', 'turpis adipiscing lorem vitae mattis nibh ligula nec', 113.94, false, 4),
('Beer - Steamwhistle', 'sapien in sapien iaculis congue vivamus metus arcu', 56.75, true, 2),
('Bacardi Mojito', 'libero nullam sit amet turpis elementum ligula', 867.52, false, 2),
('Beans - Green', 'sagittis sapien cum sociis natoque penatibus et magnis', 578.85, true, 4),
('Seedlings - Buckwheat, Organic', 'consequat nulla nisl nunc nisl duis bibendum felis', 501.89, true, 2),
('Bread Ww Cluster', 'suspendisse potenti nullam porttitor lacus at', 501.92, true, 3),
('Wine - Black Tower Qr', 'molestie hendrerit at vulputate vitae', 577.56, true, 3),
('Shrimp - 150 - 250', 'dolor sit amet consectetuer adipiscing elit', 373.99, false, 1),
('Beer - Upper Canada Light', 'blandit nam nulla integer pede justo', 223.09, true, 1),
('Thermometer Digital', 'ipsum praesent blandit lacinia erat vestibulum sed', 696.08, true, 5),
('Egg - Salad Premix', 'curae nulla dapibus dolor vel', 207.18, false, 2),
('Sausage - Andouille', 'proin risus praesent lectus vestibulum quam sapien', 100.36, true, 4),
('Whmis Spray Bottle Graduated', 'orci mauris lacinia sapien quis libero nullam sit', 94.91, true, 4),
('Beef - Cooked, Corned', 'vulputate nonummy maecenas tincidunt lacus at velit', 499.6, true, 5),
('Lobster - Cooked', 'augue vestibulum ante ipsum primis in faucibus', 93.34, false, 4),
('Turkey - Breast, Boneless Sk On', 'urna ut tellus nulla ut', 774.52, true, 5),
('Chips Potato Salt Vinegar 43g', 'eget eros elementum pellentesque quisque porta', 239.43, true, 3),
('V8 Splash Strawberry Banana', 'in quis justo maecenas rhoncus aliquam', 117.31, false, 5),
('Cheese - Fontina', 'donec vitae nisi nam ultrices libero non mattis', 981.25, false, 4),
('Ice Cream Bar - Drumstick', 'quis odio consequat varius integer ac leo', 145.61, false, 3),
('Tofu - Soft', 'iaculis congue vivamus metus arcu', 217.51, true, 3),
('Sprouts - Brussel', 'cursus id turpis integer aliquet massa id', 55.07, false, 2),
('Bread - White, Unsliced', 'vestibulum eget vulputate ut ultrices vel augue vestibulum', 578.46, true, 5),
('Cheese - Ermite Bleu', 'ipsum dolor sit amet consectetuer', 342.43, true, 1),
('Mushroom - Chanterelle, Dry', 'mattis nibh ligula nec sem', 59.43, false, 2),
('Pepper - Cayenne', 'vestibulum aliquet ultrices erat tortor sollicitudin', 682.33, false, 2),
('Wine - Zinfandel Rosenblum', 'eu est congue elementum in hac habitasse platea', 661.73, false, 4),
('Bacardi Raspberry', 'lacinia aenean sit amet justo morbi ut', 333.63, false, 4),
('Bread - Triangle White', 'aliquam erat volutpat in congue etiam', 889.16, true, 4),
('Sambuca Cream', 'vestibulum vestibulum ante ipsum primis in faucibus', 192.62, false, 2);
